version: "3"

services:
  pspdfkit1:
    image: "springboot-activemq-consumer:0.0.1-SNAPSHOT"
    expose:
      - "8083"
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - pspdfkit1
    ports:
      - "8083:4000"